### ISSUE TITLE
Bug: Adding Metric attribute always results in error.

### ISSUE THREAD

**Issue by roelvandenbrand** [awslabs/aws-lambda-powertools-dotnet#283]
### Expected Behaviour

A metric viewable in Cloudwatch

### Current Behaviour

Lambda will start and go a few lines into the function handler. We are able to inject the dynamodb connections. And possibly around the first call to DynamoDB it goes like this, but it is not clear what is needed to fix this.

fail	System.InvalidOperationException: Unable to determine range key from index name
   at AWS.Lambda.Powertools.Metrics.MetricsAspectHandler.OnException[T](AspectEventArgs eventArgs, Exception exception)
 

### Code snippet

```csharp
[Metrics(Namespace = "nl.my.namespace", Service = "Print", RaiseOnEmptyMetrics = false, CaptureColdStart = true)]
    public async Task<PrintResponse> FunctionHandlerAsync(PrintRequest input, ILambdaContext context)
```

### Possible Solution

Adding the correct attributes in the models for the Object persistence model we have implemented. Even the ones we do not use. If that works I will update this bugreport.

### Steps to Reproduce

Add the metric attribute to a Function handler.

[Metrics(Namespace = "nl.my.namespace", Service = "Print", RaiseOnEmptyMetrics = false, CaptureColdStart = true)]

### AWS Lambda Powertools for .NET version

1.2.0

### AWS Lambda function runtime

dotnet6

### Debugging logs

```csharp
fail	System.InvalidOperationException: Unable to determine range key from index name
   at AWS.Lambda.Powertools.Metrics.MetricsAspectHandler.OnException[T](AspectEventArgs eventArgs, Exception exception)
   at AWS.Lambda.Powertools.Common.MethodAspectAttribute.WrapAsync[T](Func`2 target, Object[] args, AspectEventArgs eventArgs)
   at lambda_method1(Closure , Stream , ILambdaContext , Stream )
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
   at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 55
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176
```

**Comment by roelvandenbrand** [comment]
When only using the Trace attribute it gives almost the same error:

System.InvalidOperationException: Unable to determine range key from index name
   at AWS.Lambda.Powertools.Tracing.Internal.TracingAspectHandler.OnException[T](AspectEventArgs eventArgs, Exception exception)
   at AWS.Lambda.Powertools.Common.MethodAspectAttribute.WrapAsync[T](Func`2 target, Object[] args, AspectEventArgs eventArgs)
   at lambda_method1(Closure , Stream , ILambdaContext , Stream )
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
   at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 55
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176

**Comment by roelvandenbrand** [comment]
Even the logging powertool has the same error:

System.InvalidOperationException: Unable to determine range key from index name
   at AWS.Lambda.Powertools.Logging.Internal.LoggingAspectHandler.OnException[T](AspectEventArgs eventArgs, Exception exception)
   at AWS.Lambda.Powertools.Common.MethodAspectAttribute.WrapAsync[T](Func`2 target, Object[] args, AspectEventArgs eventArgs)
   at lambda_method1(Closure , Stream , ILambdaContext , Stream )
   at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
   at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 55
   at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176

**Comment by roelvandenbrand** [comment]
It appears a different error which is not handler correctly and this botches up the powertools so it almost is like it happened there.

**Comment by hjgraca** [comment]
@roelvandenbrand thanks for raising an issue. The error message is coming from DynamoDB (if you remove the Powertools annotations you should see the same exception). It might be a configuration issue on DynamoDB code. Are you using attributes to annotate your classes? have a look at the docs [here(DynamoDBGlobalSecondaryIndexHashKey) ](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DeclarativeTagsList.html), could you share a bit more of the code? thanks.

**Comment by hjgraca** [comment]
@roelvandenbrand Any update on my comments above, did you mange to fix the issue?

**Comment by roelvandenbrand** [comment]
Yes, sorry for the late reply. With the fix in my dynamodb component that error disappeared. But still, an underlying error was mostly obscured by the powertools handling of the error. I am going to test it again soon.

**Comment by hjgraca** [comment]
Thanks @roelvandenbrand, I see what you mean, although the error message `System.InvalidOperationException: Unable to determine range key from index name` is from DynamoDB it is wrapped in a Powertools error messsage.
Maybe we can work and improve that to show the originating stack trace.

**Comment by roelvandenbrand** [comment]
That would be nice. Now it was a quite clear message, but with an unclear message, it would be hard to find the origin.

**Comment by hjgraca** [comment]
Closing this issue. This issue might have highlighted the need to expose stack trace from the originating exception if there is no exception handling and it cascades to the handler and is caught by Powertools. 
Will discuss in opening an issue for that.
